// Generated by scripts/migration.ts from src/main/storage/migration. Do not edit.

export const migrations = [
  {
    id: "20260906234153_drafts",
    statements: [
      "CREATE TABLE `blob` (\n\t`id` text PRIMARY KEY,\n\t`data` blob NOT NULL\n);",
      "CREATE TABLE `document` (\n\t`key` text PRIMARY KEY,\n\t`value` text NOT NULL\n);",
    ],
  },
  {
    id: "20260906234220_state",
    statements: [
      "CREATE TABLE `state` (\n\t`name` text NOT NULL,\n\t`key` text NOT NULL,\n\t`value` text NOT NULL,\n\t`updated_at` integer NOT NULL,\n\tCONSTRAINT `state_pk` PRIMARY KEY(`name`, `key`)\n);",
    ],
  },
  {
    id: "20260907031611_blob-touched",
    statements: ["ALTER TABLE `blob` ADD `touched_at` integer DEFAULT 0 NOT NULL;"],
  },
]
